#!/bin/bash

#parameters
#runme_ascii [FACTOR [DPI [SEED]]]
if [ $# -eq 1 ]; then
  FACTOR=$1
  DPI="300"
  SEED=$RANDOM
elif [ $# -eq 2 ]; then
  FACTOR=$1
  DPI=$2
  SEED=$RANDOM
elif [ $# -eq 3 ]; then
  FACTOR=$1
  DPI=$2
  SEED=$3
else
  FACTOR="0.01"
  DPI="300"
  SEED=$RANDOM
fi 


#generate font
../generate -i ../Andika-R.ttf --no-scramble --seed $SEED --shake $FACTOR --components 2>/dev/null
if [ ! -f Andika-$FACTOR-$SEED.ttf ]; then
  echo "Error creating font!"
  exit -1
fi

#generate test text
echo "0 1 2 3 4 5 6 7 8 9" >alphabet.txt
echo "a b c d e f g h i j" >>alphabet.txt
echo "k l m n o p q r s t" >>alphabet.txt
echo "u v w x y z A B C D" >>alphabet.txt
echo "E F G H I J K L M N" >>alphabet.txt
echo "O P Q R S T U V W X" >>alphabet.txt
echo "Y Z ." >>alphabet.txt


###CRACKING starts###

rm -f alphabet.png

#time
START=$(date +%s.%N)

#create visual data
convert -density $DPI -font ./Andika-$FACTOR-$SEED.ttf alphabet.txt alphabet-$FACTOR-$DPI-$SEED.png

#ocr
>alphabet-$FACTOR-$DPI-$SEED.txt
#gocr
gocr alphabet-$FACTOR-$DPI-$SEED.png >>alphabet-$FACTOR-$DPI-$SEED.txt

#time
END=$(date +%s.%N)


###Results###


#adjust character spacing
sed -i 's/ //g' alphabet-$FACTOR-$DPI-$SEED.txt
sed -i 's/\(.\)/\1 /g' alphabet-$FACTOR-$DPI-$SEED.txt

#stats
echo -n "$FACTOR,$DPI,$SEED,"
wdiff -s -1 -2 -3 alphabet.txt alphabet-$FACTOR-$DPI-$SEED.txt |grep alphabet-$FACTOR-$DPI-$SEED.txt |cut -d' ' -f6 |cut -d "%" -f1 |tr -d '\n'
echo -n ","
echo "$END - $START" |bc

