#!/opt/local/bin/python2


####################################################
#
# Generate scrambled fonts.
#
# This is a very basic script to generate scrambled
# fonts. Intentionally, only the lower case letters
# are scrambled to provide an easy understanding of
# the mechanism of font scrambling.
#
# Copyright (c) by Tamas Jursonovics
# http://jursonovics.com
#
# prerequisites: fontforge, python-fontforge
#
####################################################


import fontforge;                       #import fontforge python libraries
import string
import random
import sys
import os.path
import argparse


parser = argparse.ArgumentParser(description='Font scrambler.')
parser.add_argument('-i',type=argparse.FileType('r'),help='an input font file',required=True)
parser.add_argument('--seed',type=int,help='only for testing, allow recreation of random table')
parser.add_argument('--shake',action='store_true',help='shake points to avoid hash attack')
args = parser.parse_args()

if args.seed is not None:               #for demo purposes only: allow recreation of scrambler table
  variant=str(args.seed)
  random.seed(variant)
else:
  variant=str(random.randrange(1000000000,9999999999))
  random.seed()


bfont=fontforge.open(args.i.name)       #open a non-scrambled, source font
nfont=fontforge.font()                  #create an placeholder for the scrambled font
tbl=open(bfont.familyname + "_" + variant + ".txt", 'w') #create the scrambler table


displaychar="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!()+,-./:;<=>?"
ascii=list(displaychar)                 #create scrambling table
scrmx=list(displaychar)            
random.shuffle(scrmx)                   #scramble the letters


for b, n in zip(ascii, scrmx):          #scramble the font
  bfont.selection.select(b)
  bfont.copy()
  nfont.selection.select(n)
  nfont.paste()


if args.shake is not None:              #shake font
  for g in nfont.glyphs():              #loop over all glyphs

      for i in range(0, g.layer_cnt):   #loop over all layers
      
        g.activeLayer=i
        l=g.layers[g.activeLayer]

        for c in l:                     #loop over all contours

          for p in c:                   #loop over all points

            d=0.05                      #5% shake factor
            p.x=p.x*random.uniform(1-d,1+d)
            p.y=p.y*random.uniform(1-d,1+d)
  
        g.layers[g.activeLayer] = l     #save layer


tbl.write(''.join(ascii) + "\n")        #write scrambler table
tbl.write(''.join(scrmx))


nfont.fontname=bfont.fontname           #copy properties
nfont.familyname=bfont.familyname
nfont.version=variant
nfont.copyright=bfont.copyright
nfont.ascent=bfont.ascent
nfont.descent=bfont.descent
nfont.em=bfont.em
nfont.upos=bfont.upos
nfont.uwidth=bfont.uwidth
nfont.weight=bfont.weight
nfont.comment="Scrambled font created by FontScrambler, please see the scrambling table to encode text"
nfont.generate(bfont.familyname + "_" + variant + ".ttf")   #save scrambled font
bfont.close()
nfont.close()
tbl.close()

