#!/bin/bash

OUT="output.csv"
#test several combination
rm -f lorem-*
rm -f ascii-*
rm -f Andika-*
rm -f $OUT

echo "#FACTOR,DPI,SEED,SUCCESS,TIME,FACTOR,DPI,mean(SUCCESS),std.dev(SUCCESS)" |tee -a $OUT

for DPI in $(seq 200 100 600); do
  for FACTOR in $(seq 0.01 0.01 0.09); do
#    echo "$DPI $FACTOR"
    X=""
    for n in {1..20}; do
      X="$(./runme_ascii $FACTOR $DPI)
$X"
    done
    echo "${X::-1}" |tee -a $OUT
    echo "${X::-1}" |awk -F',' -v factor=$FACTOR -v dpi=$DPI '{n+=1;sum+=$4;array[n]=$4} END {for (x=1;x<n;x++) sumsq+=(array[x]-(sum/n))**2; print ",,,,," factor "," dpi "," sum/n "," sqrt(sumsq/n)}' |tee -a $OUT

#    echo ""
#    echo ""
  done
done



#awk '{n++; sum+=$1; sumsq+=$1*$1}END{print sum/n "," sqrt(sumsq/NR - (sum/NR)**2)}'


